#######################################################################################
# Book settings
title: Argo Online School
author: Euro Argo
logo: ./images/logoAoS.png
exclude_patterns: [Prueba*.ipynb, Info.ipynb] 

#######################################################################################
# Execution settings
execute:
  execute_notebooks: off

#######################################################################################
# HTML-specific settings
html:
  use_repository_button: true

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate

repository:
  url: https://github.com/euroargodev/argoonlineschool
  branch: master  # Which branch of the repository should be used when creating links


latex:
  latex_documents:
    targetname: book.tex
